# Generated by Django 2.2.1 on 2020-04-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='stage',
            field=models.IntegerField(choices=[(0, 'Рядовой'), (1, 'Прапорщик'), (2, 'Лейтенант'), (3, 'Майор'), (4, 'Полковник'), (5, 'Генерал')], default=0),
        ),
    ]
