# Generated by Django 2.2.1 on 2020-04-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200404_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='bd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='dd',
            field=models.DateField(blank=True, null=True),
        ),
    ]
