# Generated by Django 2.2.1 on 2020-04-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200404_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='karma',
            new_name='exp',
        ),
    ]
