# Generated by Django 2.2.1 on 2020-04-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200404_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='urlVK',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
