# Generated by Django 2.2.1 on 2020-04-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200404_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='stage',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
