# Generated by Django 2.2.1 on 2020-04-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_photo_isavatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='isAvatar',
            field=models.IntegerField(default=0),
        ),
    ]
