# Generated by Django 2.2.1 on 2020-04-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200404_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='isAvatar',
            field=models.BooleanField(default=False),
        ),
    ]
