# Generated by Django 2.2.1 on 2020-04-05 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='urlVK',
            new_name='user',
        ),
    ]
