# Generated by Django 2.2.1 on 2020-04-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200405_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='path',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
